# Используем официальный образ Python
FROM python:3.13-slim

# Установка системных зависимостей
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

# Копируем файл зависимостей и устанавливаем их
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
