# Проверка стиля и тестов
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Получение кода
        uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Установка зависимостей
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Проверка стиля
        run: pre-commit run --all-files
      - name: Запуск тестов
        run: pytest
