# Проверка стиля и тестов
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Получение кода
        uses: actions/checkout@v4
      - name: Вход в реестр GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Сборка и публикация образа
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci
          push: true
          tags: ghcr.io/${{ github.repository }}:ci

  test:
    needs: build-image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:ci
    steps:
      - name: Получение кода
        uses: actions/checkout@v4
      - name: Установка зависимостей для разработки
        run: pip install -r requirements-dev.txt
      - name: Проверка стиля
        run: pre-commit run --all-files
      - name: Запуск тестов
        run: pytest
